//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Masny.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SyncMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SyncMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Masny.Application.Resources.SyncMessage", typeof(SyncMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding new comments is over..
        /// </summary>
        public static string CommentAddEnd {
            get {
                return ResourceManager.GetString("CommentAddEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while adding a comment with Post Id = {0}.
        /// </summary>
        public static string CommentAddError {
            get {
                return ResourceManager.GetString("CommentAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding new comments started...
        /// </summary>
        public static string CommentAddStart {
            get {
                return ResourceManager.GetString("CommentAddStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion of comments is over..
        /// </summary>
        public static string CommentDeleteEnd {
            get {
                return ResourceManager.GetString("CommentDeleteEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion of comments started...
        /// </summary>
        public static string CommentDeleteStart {
            get {
                return ResourceManager.GetString("CommentDeleteStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating comments is over..
        /// </summary>
        public static string CommentUpdateEnd {
            get {
                return ResourceManager.GetString("CommentUpdateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating comments started...
        /// </summary>
        public static string CommentUpdateStart {
            get {
                return ResourceManager.GetString("CommentUpdateStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding new people is over..
        /// </summary>
        public static string PersonAddEnd {
            get {
                return ResourceManager.GetString("PersonAddEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding new people started...
        /// </summary>
        public static string PersonAddStart {
            get {
                return ResourceManager.GetString("PersonAddStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion of people is over..
        /// </summary>
        public static string PersonDeleteEnd {
            get {
                return ResourceManager.GetString("PersonDeleteEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion of people started...
        /// </summary>
        public static string PersonDeleteStart {
            get {
                return ResourceManager.GetString("PersonDeleteStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating people is over..
        /// </summary>
        public static string PersonUpdateEnd {
            get {
                return ResourceManager.GetString("PersonUpdateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating people started...
        /// </summary>
        public static string PersonUpdateStart {
            get {
                return ResourceManager.GetString("PersonUpdateStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding new posts is over..
        /// </summary>
        public static string PostAddEnd {
            get {
                return ResourceManager.GetString("PostAddEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while adding a post with User Id = {0}.
        /// </summary>
        public static string PostAddError {
            get {
                return ResourceManager.GetString("PostAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding new posts started...
        /// </summary>
        public static string PostAddStart {
            get {
                return ResourceManager.GetString("PostAddStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion of posts is over..
        /// </summary>
        public static string PostDeleteEnd {
            get {
                return ResourceManager.GetString("PostDeleteEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion of posts started...
        /// </summary>
        public static string PostDeleteStart {
            get {
                return ResourceManager.GetString("PostDeleteStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating posts is over..
        /// </summary>
        public static string PostUpdateEnd {
            get {
                return ResourceManager.GetString("PostUpdateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating posts started...
        /// </summary>
        public static string PostUpdateStart {
            get {
                return ResourceManager.GetString("PostUpdateStart", resourceCulture);
            }
        }
    }
}
